name: Sync main with master

on:
  push:
    branches:
      - master
  workflow_dispatch: # 允许手动触发

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync main branch with master
        run: |
          git checkout main
          git pull
          git merge origin/master
          git push origin main
